os:
  - linux
services:
  - docker
language: node_js
node_js:
  - '12.13.1'
cache:
  directories:
    - node
    - node_modules
    - $HOME/.m2
env:
  global:
    - NODE_VERSION=12.13.1
    - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    - SPRING_JPA_SHOW_SQL=false
    - JHI_DISABLE_WEBPACK_LOGS=true
    - NG_CLI_ANALYTICS="false"
    - MAVEN_USER_HOME=$HOME/.m2/repository/
dist: trusty
before_install:
  - |
    if [[ $JHI_JDK = '8' ]]; then
      echo '*** Using OpenJDK 8'
    else
      echo '*** Using OpenJDK 11 by default'
      sudo add-apt-repository ppa:openjdk-r/ppa -y
      sudo apt-get update -q
      sudo apt-get install -y openjdk-11-jdk -y
      sudo update-java-alternatives -s java-1.11.0-openjdk-amd64
      java -version
    fi
  - java -version
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
  - nvm install $NODE_VERSION
  - npm install -g npm
  - node -v
  - npm -v
  #- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - CHROME_MAIN_VERSION=`google-chrome-stable --version | sed -E 's/(^Google Chrome |\.[0-9]+ )//g'`
  - CHROMEDRIVER_VERSION=`curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_MAIN_VERSION"`
  - curl "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -O
  - unzip chromedriver_linux64.zip -d ~/bin
install:
  - npm install
script:
  - whereis google-chrome-stable
  - chmod +x mvnw
  - ./mvnw -ntp checkstyle:check
  - ./mvnw -ntp clean verify
  #- ./mvnw -ntp Pprod clean package -Dmaven.test.skip=true
  - npm run cleanup && npm run webpack:build:main
  - ./mvnw -ntp com.github.eirslett:frontend-maven-plugin:npm -Dfrontend.npm.arguments='run test' -Dmaven.repo.local=$MAVEN_USER_HOME
  - if [ $TRAVIS_PULL_REQUEST == "false" ]; then ./mvnw -ntp org.jacoco:jacoco-maven-plugin:prepare-agent initialize sonar:sonar -Dsonar.organization=fhvmasterv2 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN; fi

  - ./mvnw -ntp verify -Pprod -DskipTests
notifications:
  webhooks:
    on_success: change # options: [always|never|change] default: always
    on_failure: always # options: [always|never|change] default: always
    on_start: false # default: false

addons:
  chrome: stable

  sonarcloud:
    organization: 'fhvmasterv2'
    token:
      secure: 'i5neQp5qqbWzsMyY/vx4AUXOIjlk1+CZ3E3cZuWbE+2XeQ/nYxV9k9coTE+C7F8bNo3geWxOk7Xuav5xyGk7Nu0chcJQfFc/VVAFzark0F9XAkCi9joCjI/SaiC9hu9YpV8OLyhsJYmjLl7EX2NNrYjYhrW6kgcx7a5yGt5Nu4T9cH8lrH65OWixA51q4xlhos/AssHMaxRY6BYvVFvopmXaG6mk3y87sFnXPRwlpu9fxb0cb0K4LRgD/GVAoGk4/mqUgduGNUD847GpPDhWBNc5zxfx8Eth3mWguzveoAt4GLBNFrEmfZ8fnrwPcp91WIOjalkl3Uugp9zm7CLPvUFbQATDEwQlGabVBAkkKHAH9lpfV8rnYp4WoWvqAH1smtzP/lKT6HJ+P30ruGLzc50/2hqFjrPo/T+8HbvSUySJUnYmIkr+dtntWvOW/Y3erZxMcXHhWGz4Xe+lO3QC14ypgJyuyKvLT3gyTzMkTNKuvmyoMUGBLTfjC0UX/DMIyKEPHi1p9IecTqcjIg6QLdUOnw1nwQsTgsppzGpgTWGExCMoAE8V/4WQXqLy3sTtXsm/HyBuceLmNZf8FearL8JBMm8x0JToXrx6AakKun6vdNn8nDoKtXX9gy5Sp93n68zEFYTaBDtgz2b+TSiiCXXLGk6yUV0QVVcZfmOkYhI='
